import type { Metadata } from "next";
import localFont from "next/font/local";
import styles from "../page.module.css";
import { NextUIProvider } from "@nextui-org/react";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Planets",
  description: "Generated by me",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <NextUIProvider>
          <div className={styles.page}>
            <main className={styles.main}>{children}</main>
          </div>
        </NextUIProvider>
      </body>
    </html>
  );
}
